/**
 * executorCriticalDoc.ts
 *
 * Executor agent for the Critical Document pipeline.
 * Pure function — no React, no browser APIs, no LLM.
 *
 * Responsibility:
 *   1. Normalize raw user inputs (trim, uppercase names, enforce date format).
 *   2. Render a printable HTML preview of the filled form.
 */

import type { DocField, CriticalDocExecutionResult } from './types'
import { logger } from './logger'

const agentLogger = logger.setDomain('agent')

// ── Normalisation helpers ─────────────────────────────────────────────────

function normalizeName(value: string): string {
  return value.trim().toUpperCase()
}

function normalizeDate(value: string): string {
  // Accept dd/mm/yyyy or dd-mm-yyyy or ddmmyyyy and normalise to dd/mm/yyyy
  const stripped = value.trim().replace(/[-.\s]/g, '/')
  // If already dd/mm/yyyy, return as-is
  if (/^\d{2}\/\d{2}\/\d{4}$/.test(stripped)) return stripped
  // Try ddmmyyyy → dd/mm/yyyy
  if (/^\d{8}$/.test(stripped)) {
    return `${stripped.slice(0, 2)}/${stripped.slice(2, 4)}/${stripped.slice(4)}`
  }
  return value.trim()
}

function normalizeCode(value: string): string {
  return value.trim().replace(/\s/g, '')
}

function normalizeSubjects(value: string): string {
  // Normalise spacing around commas: "041 , 042,043" → "041,042,043"
  return value.trim().split(',').map(s => s.trim()).join(',')
}

/**
 * Applies field-type-aware normalisation to a single value.
 */
function normalizeField(field: DocField, raw: string): string {
  if (!raw) return ''
  switch (field.id) {
    case 'candidateName':
    case 'fatherName':
    case 'motherName':
      return normalizeName(raw)
    case 'dob':
      return normalizeDate(raw)
    case 'rollNumber':
    case 'schoolCode':
    case 'examCentreCode':
      return normalizeCode(raw)
    case 'subjects':
      return normalizeSubjects(raw)
    default:
      return raw.trim()
  }
}

// ── HTML renderer ─────────────────────────────────────────────────────────

function renderHtml(
  fieldsManifest: DocField[],
  normalizedInputs: Record<string, string>
): string {
  const rows = fieldsManifest
    .map(f => {
      const value = normalizedInputs[f.id] ?? ''
      const displayValue = value || '<span style="color:#999">—</span>'
      const requiredMark = f.required ? ' <span style="color:red">*</span>' : ''
      return `
      <tr>
        <td style="padding:6px 12px;font-weight:600;width:40%;border-bottom:1px solid #e5e7eb">
          ${f.label}${requiredMark}
        </td>
        <td style="padding:6px 12px;border-bottom:1px solid #e5e7eb">
          ${displayValue}
        </td>
      </tr>`
    })
    .join('')

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>CBSE Exam Form Preview</title>
  <style>
    body { font-family: Arial, sans-serif; font-size: 13px; color: #111; margin: 32px; }
    h1   { font-size: 18px; text-align: center; margin-bottom: 4px; }
    h2   { font-size: 13px; text-align: center; color: #555; margin-bottom: 24px; }
    table { width: 100%; border-collapse: collapse; border: 1px solid #d1d5db; }
    tr:nth-child(even) { background: #f9fafb; }
    .footer { margin-top: 32px; font-size: 11px; color: #888; text-align: center; }
  </style>
</head>
<body>
  <h1>Central Board of Secondary Education</h1>
  <h2>Examination Registration Form — Preview</h2>
  <table>
    <tbody>${rows}
    </tbody>
  </table>
  <div class="footer">
    Generated by Q-AODS Critical Document Pipeline · ${new Date().toISOString()}
  </div>
</body>
</html>`
}

// ── Agent ─────────────────────────────────────────────────────────────────

export interface DocExecutorInput {
  fieldsManifest: DocField[]
  userInputs: Record<string, string>
}

export function runDocExecutor(input: DocExecutorInput): CriticalDocExecutionResult {
  agentLogger.info('DOC_EXECUTOR_START', { fieldCount: input.fieldsManifest.length })

  // 1. Normalise all inputs
  const normalizedInputs: Record<string, string> = {}
  for (const field of input.fieldsManifest) {
    const raw = input.userInputs[field.id] ?? ''
    normalizedInputs[field.id] = normalizeField(field, raw)
  }

  // 2. Render HTML preview
  const generatedDoc = renderHtml(input.fieldsManifest, normalizedInputs)

  agentLogger.info('DOC_EXECUTOR_COMPLETE', {
    normalizedFieldCount: Object.keys(normalizedInputs).length,
    docChars: generatedDoc.length,
  })

  return { normalizedInputs, generatedDoc }
}
